version: "3.8"

services:
  db:
    image: mariadb:10.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: csms
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
